# Generated by Django 6.0.3 on 2026-04-13 10:12

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_batteryoption_delete_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
