# Generated by Django 6.0.3 on 2026-04-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_reservation_user_reservation_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_name',
            new_name='name',
        ),
    ]
