# Generated by Django 6.0.3 on 2026-04-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_rename_user_name_reservation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='user_name',
        ),
    ]
