# Generated by Django 6.0.3 on 2026-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_rename_name_reservation_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
